### ISSUE TITLE
Add metrics-server as a requirement

### ISSUE THREAD

**Issue by JarredOlson** [Datastillery/charts#124]
To get kubernetes metrics about resource utilization the metrics-server needs to be installed.  This can be added as a dependency in the requirements.yaml file.

```
dependencies:
  - name: metrics-server
    version: 2.8.7
    repository: "@stable"
```

https://github.com/helm/charts/tree/master/stable/metrics-server
